name: Bug Report
description: |
  Please report a bug of deny-self-approve.
  If you're not sure if it's a bug or not, please use the template `Support Request` instead.
labels:
  - bug
body:
  - type: textarea
    id: info
    attributes:
      label: Version and OS
      description: |
        Please use the latest version.
        If you checked multiple versions, please write the result too.
        e.g. This issue occurs using deny-self-approve v0.2.1 and v0.2.2, but doesn't occur using v0.2.0.
      value: |
        ```console
        $ deny-self-approve -v

        ```
    validations:
      required: true
  - type: textarea
    id: overview
    attributes:
      label: Overview
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce
      description: |
        Please see [the guide](https://github.com/suzuki-shunsuke/oss-contribution-guide#write-good-how-to-reproduce) too.
        If possible, please reproduce the issue in a public repository.
        And please explain the review status.
      value: |
        Executed command and output:

        ```console
        $ 
        ```
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
    validations:
      required: true
  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual behaviour
    validations:
      required: true
  - type: textarea
    id: note
    attributes:
      label: Note
    validations:
      required: false
