name: Support Request
description: |
  Please use this template when you face any problem (not bug) and need our help.
  If you're not sure if it's a bug or not, please use this template.
labels:
  - support-request
body:
  - type: textarea
    id: info
    attributes:
      label: Version and OS
      description: |
        Please use the latest version.
        If you checked multiple versions, please write the result too.
    validations:
      required: true
  - type: textarea
    id: overview
    attributes:
      label: Overview
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce
      description: |
        Please see [the guide](https://github.com/suzuki-shunsuke/oss-contribution-guide#write-good-how-to-reproduce) too.
        If possible, please reproduce the issue in a public repository.
        And please explain the review status.
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
    validations:
      required: true
  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual behaviour
    validations:
      required: true
  - type: textarea
    id: note
    attributes:
      label: Note
    validations:
      required: false
